channels:
- conda-forge
dependencies:
- python=3.13.7
- pip<=24.3.1
- pip:
  - mlflow==3.5.0
  - cloudpickle==3.1.1
  - feature-engine==1.9.3
  - numpy==2.2.5
  - pandas==2.2.3
  - psutil==7.1.0
  - pyarrow==20.0.0
  - scikit-learn==1.7.2
  - scipy==1.15.3
name: mlflow-env
